### ISSUE TITLE
sleep异常

### ISSUE THREAD

**Issue by 760286098** [izhangguapi/letsgo-farm#1]
<img width="1039" alt="image" src="https://github.com/user-attachments/assets/5e7bbca8-43e4-4522-bb58-5670fdb4ad80">
<img width="1044" alt="image" src="https://github.com/user-attachments/assets/3fdfeb88-286a-473d-9bdf-0f39e1d2c268">
sleep前判断一下t是否大于0。t可能小于0，这种情况下会异常退出

**Comment by izhangguapi** [comment]
已修复
