### ISSUE TITLE
[Errno 22] Invalid argument

### ISSUE THREAD

**Issue by cattle891240** [izhangguapi/letsgo-farm#2]
在win11系统、python24.2、8月2日的版本执行的过程中，会出现[Errno 22] Invalid argument如图：
![mytools错误](https://github.com/user-attachments/assets/e398ac8d-33ba-4e44-82a5-e98393bba92f)
然后在出现main.py创造的窗口之后，点击启动后就不会继续执行下去了。也没有其他消息反馈
![屏幕截图 2024-08-04 074730](https://github.com/user-attachments/assets/b82b19bf-75cc-47a7-9ba6-680462fd5cdf)

相比7月26日的版本虽然不会钓鱼，但是还能对农田和动物进行操作。我应该怎么改来解决新版本出现的Errno 22

**Comment by izhangguapi** [comment]
由于windows系统的文件名称不能够有英文冒号“：”，导致出现错误，mac没问题，最新版已修复。
