### ISSUE TITLE
明明没撒饵，在记录框那边就会提示已经撒饵了

### ISSUE THREAD

**Issue by cattle891240** [izhangguapi/letsgo-farm#3]
为什么明明没撒饵，在记录框那边就会提示已经撒饵了？我需要怎么修正？

![屏幕截图 2024-08-05 165323](https://github.com/user-attachments/assets/60e7c12c-171e-49ba-bce4-a0b3e23ab816)

**Comment by cattle891240** [comment]
我还发现每次开游戏都是节能的，我还得把他改成极致。

![屏幕截图 2024-08-05 182117](https://github.com/user-attachments/assets/270473f9-bc4b-42da-8348-079f0a813e81)

**Comment by Kaiwei-Lin** [comment]
> 我还发现每次开游戏都是节能的，我还得把他改成极致。
> 
> ![屏幕截图 2024-08-05 182117](https://private-user-images.githubusercontent.com/68153246/355067616-270473f9-bc4b-42da-8348-079f0a813e81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NjYxNjYsIm5iZiI6MTcyMjk2NTg2NiwicGF0aCI6Ii82ODE1MzI0Ni8zNTUwNjc2MTYtMjcwNDczZjktYmM0Yi00MmRhLTgzNDgtMDc5ZjBhODEzZTgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDE3Mzc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4YzA5Njk1N2QxOGFiZjM2NzYwODk3NmVlNTIwZTQwNzBmNDVkOTE0YjRjYTllZTlmMTc0ODI4YjFjZWRmYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yI8G1G6fDt3JxRYYC1DXV5fCl1Yw-iLJM9_nwx9ubTQ)

关于这个我在程序中修改了等待的时间，避免长时间等待让屏幕进入省电状态。
或者在程序下次运行前先点击一下屏幕，让游戏跳出省电模式

**Comment by izhangguapi** [comment]
省电模式早已做了优化，按下两次r，第一次的目的是解除省电模式，第二次才是重置。进入电模式可以有效的降低网络下行流量，对于网络环境不太好的用户有所帮助。

<img width="413" alt="image" src="https://github.com/user-attachments/assets/a2dc0e0c-886b-4e05-94f3-cbffead99640">
<img width="419" alt="image" src="https://github.com/user-attachments/assets/fc4819be-1847-4e7f-95ec-2ebdb462fad6">

**Comment by Kaiwei-Lin** [comment]
> 省电模式早已做了优化，按下两次r，第一次的目的是解除省电模式，第二次才是重置。 进入电模式可以有效的降低网络下行流量，对于网络环境不太好的用户有所帮助。 三分钟进入省电模式，十分钟自动退出游戏 <img alt="image" width="413" src="https://private-user-images.githubusercontent.com/33612298/355577309-a2dc0e0c-886b-4e05-94f3-cbffead99640.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5ODk2OTcsIm5iZiI6MTcyMjk4OTM5NywicGF0aCI6Ii8zMzYxMjI5OC8zNTU1NzczMDktYTJkYzBlMGMtODg2Yi00ZTA1LTk0ZjMtY2JmZmVhZDk5NjQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDAwMDk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkODBjMmE0MGI5OGZlOGEyODBkZWYwN2IxMTQ0NzliODcyNjc5MmMwMDllZjAyNTg3N2FhOTczNjFkYTBjNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VrqIF55iq-ey-v7-Z14I-RKs8nXTZUPXH6Zu6QkqKvg"> <img alt="image" width="419" src="https://private-user-images.githubusercontent.com/33612298/355577460-fc4819be-1847-4e7f-95ec-2ebdb462fad6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5ODk2OTcsIm5iZiI6MTcyMjk4OTM5NywicGF0aCI6Ii8zMzYxMjI5OC8zNTU1Nzc0NjAtZmM0ODE5YmUtMTg0Ny00ZTdmLTk1ZWMtMmViZGI0NjJmYWQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDAwMDk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2Y2U5ODE2ZWM2NmQwOTM1YTU0N2U1OGRiNDViODdiZThiMzIyMjY1OTY2NTFlZmU1ZGE5MmRkZDE2NTJmNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TrQ3AJan_Qh1cnF16gYrSSvzKI7qFhCeltdTeSb0Yf0">

没看到哇，因为我把种菜和放牧的线程注释了

**Comment by Kaiwei-Lin** [comment]
> 为什么明明没撒饵，在记录框那边就会提示已经撒饵了？我需要怎么修正？
> 
> ![屏幕截图 2024-08-05 165323](https://private-user-images.githubusercontent.com/68153246/355040763-60e7c12c-171e-49ba-bce4-a0b3e23ab816.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMTUzMTMsIm5iZiI6MTcyMzAxNTAxMywicGF0aCI6Ii82ODE1MzI0Ni8zNTUwNDA3NjMtNjBlN2MxMmMtMTcxZS00OWJhLWJjZTQtYTBiM2UyM2FiODE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA3MTY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMTdmNzczOTNiZTVmOTlkMjc1NGViNzM2MWFiNDM5MmMxZDEwZDVkNmNmYzlmMGJmYTExNTY1MzdlYjE3ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0UIOUOkWbSaoPTtAVTRYQkmDrLbA7RUFosE4NiE5Kog)

我发现了，不能把左边鱼塘等级挡住，挡住程序检测不到鱼塘就会判定已经撒饵

**Comment by izhangguapi** [comment]
有识图，不挡住截图区域
