### ISSUE TITLE
钓鱼没有处理调到卡牌的事件

### ISSUE THREAD

**Issue by Kaiwei-Lin** [izhangguapi/letsgo-farm#4]
钓鱼没有处理钓到卡牌的事件
调到卡牌需要点击空白区域，但是程序的逻辑是[按“g”键](https://github.com/izhangguapi/letsgo-farm/blob/82c5c84f4771be01485272439eee75922c3cab8d/letsgoFarm.py#L142)来跳过钓鱼间隔。
所以我在这里下一行添加了`pyautogui.click(x=926, y=805)`，这里的xy根据自己屏幕的位置自行更换。
或者作者有更好的方法。
总之谢谢作者写的脚本😀

**Comment by izhangguapi** [comment]
![WX20240807-032530@2x](https://github.com/user-attachments/assets/125879d7-efb0-42ff-8cdd-1f97bfd59cc1)
需要添加一个键位

**Comment by Kaiwei-Lin** [comment]
> ![WX20240807-032530@2x](https://private-user-images.githubusercontent.com/33612298/355576841-125879d7-efb0-42ff-8cdd-1f97bfd59cc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5ODk1MDcsIm5iZiI6MTcyMjk4OTIwNywicGF0aCI6Ii8zMzYxMjI5OC8zNTU1NzY4NDEtMTI1ODc5ZDctZWZiMC00MmZmLThjZGQtMWY5N2JmZDU5Y2MxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDAwMDY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2YTdlZWMzMzQwM2RhNzY5Nzg3OWY0OWI0YjMyZDg3NTBmMDg0ZmNjNTYzYzJkNzllOTA4NmE1NTYzYWQ1NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nXpyBIzR7CTEKM3SVb_nEp6FnId_E7dKLuvR_JHCt0s) 需要添加一个键位

啊确实。起床遇到一个问题，掉线了，然后忘记测量确认的位置和截图了/(ㄒoㄒ)/~~
