### ISSUE TITLE
无法勾选是为什么呢

### ISSUE THREAD

**Issue by LarissaLycoris** [izhangguapi/letsgo-farm#9]
如图
![IMG_20241119_075814](https://github.com/user-attachments/assets/a3a87898-e355-4892-ba24-c7323ef8f261)
启用按钮是灰色的，想关闭无法关闭

**Comment by izhangguapi** [comment]
现在无人机直接全部执行，未针对单个功能进行控制

**Comment by LarissaLycoris** [comment]
> 现在无人机直接全部执行，未针对单个功能进行控制

这个掉线会重连么

**Comment by izhangguapi** [comment]
不会

**Comment by LarissaLycoris** [comment]
> 不会

好像鱼塘那个单独执行没去掉？他每次执行全部前会单独执行一次鱼塘，在执行全部，有办法不让他单独执行多一次鱼塘，就执行全部吗，因为执行全部那里我可以设置不走鱼塘

**Comment by izhangguapi** [comment]
没有执行鱼塘，只是识别鱼塘成熟时间

**Comment by LarissaLycoris** [comment]
> 没有执行鱼塘，只是识别鱼塘成熟时间

好的，谢谢。在没有gpu的轻服务器好像不行，后续打算适配么？我可以提供个服务器测试一下，虽然是水龙头服务器

**Comment by LarissaLycoris** [comment]
> 没有打算适配，开发这个程序的本意是方便自己使用，上传到github只是为了分享给有能力的人，针对自己的需求进行更改

好的，谢谢，可关闭问题
